{
 "cells": [
  {
   "cell_type": "markdown",
   "source": [
    "# Welcome to ANDI!\n",
    "This notebook will guide you throughout our project! Let's start by setting up our environment"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "#select your venv\n",
    "# ! source venv/bin/activate\n",
    "! ! pip install -r requirements.txt --find-links https://download.pytorch.org/whl/torch_stable.html"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "\n",
    "import gdown\n",
    "import shutil\n",
    "import os\n",
    "gdown.download(\"https://drive.google.com/uc?export=download&id=1tKAhkas5sCnIYurURylS63ZgBTdsrg_Q\",\"data/data_split2.zip\")\n",
    "gdown.download(\"https://drive.google.com/uc?export=download&id=1YXlG77XbMA0a4d12qcUSLa9sMp4rk6Nx\",\"data/unseen_data_test.zip\")\n",
    "\n",
    "shutil.unpack_archive(\"data/data_split2.zip\", \"data_split2\")\n",
    "shutil.unpack_archive(\"data/unseen_data_test.zip\",\"unseen_test_set\")\n",
    "os.remove(\"data/unseen_data_test.zip\")\n",
    "#lets keep data_split2.zip just in case..."
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "# This section is for training. If you already trained a model, you can skip ahead to the next section\n",
    "\n",
    "Training a model is easy! To see the available options :"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "! python run_train.py -h"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Where the dataset corresponds to the different experiences as describe in our report.\n",
    "\n",
    "Let's try something simple!"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "sh: 1: source: not found\r\n",
      "\u001B[34m\u001B[1mtrain: \u001B[0mweights=models/yolov5/yolov5s.pt, cfg=, data=/home/jonathan/PycharmProjects/IFT6759_Deep_learning/data/data_split2/data_split2.yaml, hyp=models/yolov5/data/hyps/hyp.scratch-low.yaml, epochs=2, batch_size=-1, imgsz=320, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=models/yolov5/runs/train, name=exp, exist_ok=True, quad=False, cos_lr=False, label_smoothing=0.0, patience=5, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest\r\n",
      "\u001B[34m\u001B[1mgithub: \u001B[0mskipping check (not a git repository), for updates see https://github.com/ultralytics/yolov5\r\n",
      "YOLOv5 🚀 69d373f torch 1.11.0+cu113 CUDA:0 (NVIDIA GeForce GTX 1660 Ti, 5945MiB)\r\n",
      "\r\n",
      "\u001B[34m\u001B[1mhyperparameters: \u001B[0mlr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0\r\n",
      "\u001B[34m\u001B[1mWeights & Biases: \u001B[0mrun 'pip install wandb' to automatically track and visualize YOLOv5 🚀 runs (RECOMMENDED)\r\n",
      "\u001B[34m\u001B[1mTensorBoard: \u001B[0mStart with 'tensorboard --logdir models/yolov5/runs/train', view at http://localhost:6006/\r\n",
      "Overriding model.yaml nc=80 with nc=14\r\n",
      "\r\n",
      "                 from  n    params  module                                  arguments                     \r\n",
      "  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              \r\n",
      "  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                \r\n",
      "  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   \r\n",
      "  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               \r\n",
      "  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 \r\n",
      "  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              \r\n",
      "  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 \r\n",
      "  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              \r\n",
      "  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 \r\n",
      "  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 \r\n",
      " 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              \r\n",
      " 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          \r\n",
      " 12           [-1, 6]  1         0  models.common.Concat                    [1]                           \r\n",
      " 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          \r\n",
      " 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              \r\n",
      " 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          \r\n",
      " 16           [-1, 4]  1         0  models.common.Concat                    [1]                           \r\n",
      " 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          \r\n",
      " 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              \r\n",
      " 19          [-1, 14]  1         0  models.common.Concat                    [1]                           \r\n",
      " 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          \r\n",
      " 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              \r\n",
      " 22          [-1, 10]  1         0  models.common.Concat                    [1]                           \r\n",
      " 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          \r\n",
      " 24      [17, 20, 23]  1     51243  models.yolo.Detect                      [14, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]\r\n",
      "Model summary: 270 layers, 7057387 parameters, 7057387 gradients\r\n",
      "\r\n",
      "Transferred 343/349 items from models/yolov5/yolov5s.pt\r\n",
      "\u001B[34m\u001B[1mAutoBatch: \u001B[0mComputing optimal batch size for --imgsz 320\r\n",
      "\u001B[34m\u001B[1mAutoBatch: \u001B[0mCUDA:0 (NVIDIA GeForce GTX 1660 Ti) 5.81G total, 0.06G reserved, 0.05G allocated, 5.69G free\r\n",
      "      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "     7057387           0         0.168           124           nan        (1, 3, 320, 320)                    list\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "     7057387           0         0.252          66.1           nan        (2, 3, 320, 320)                    list\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "     7057387           0         0.413         66.21           nan        (4, 3, 320, 320)                    list\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "     7057387           0         0.780         68.07           nan        (8, 3, 320, 320)                    list\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 154, in train\r\n",
      "    batch_size = check_train_batch_size(model, imgsz)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 19, in check_train_batch_size\r\n",
      "    return autobatch(deepcopy(model).train(), imgsz)  # compute optimal batch size\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/autobatch.py\", line 49, in autobatch\r\n",
      "    y = profile(img, model, n=3, device=device)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/utils/torch_utils.py\", line 119, in profile\r\n",
      "    y = m(x)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "     7057387           0         1.518         90.23           nan       (16, 3, 320, 320)                    list\r\n",
      "\u001B[34m\u001B[1mAutoBatch: \u001B[0mUsing batch-size 55 for CUDA:0 5.22G/5.81G (90%)\r\n",
      "Scaled weight_decay = 0.0004296875\r\n",
      "\u001B[34m\u001B[1moptimizer:\u001B[0m SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias\r\n",
      "\u001B[34m\u001B[1mtrain: \u001B[0mScanning '/home/jonathan/PycharmProjects/IFT6759_Deep_learning/data/data_\u001B[0m\r\n",
      "\u001B[34m\u001B[1mval: \u001B[0mScanning '/home/jonathan/PycharmProjects/IFT6759_Deep_learning/data/data_sp\u001B[0m\r\n",
      "Plotting labels to models/yolov5/runs/train/exp/labels.jpg... \r\n",
      "\r\n",
      "\u001B[34m\u001B[1mAutoAnchor: \u001B[0m5.65 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅\r\n",
      "Image sizes 320 train, 320 val\r\n",
      "Using 8 dataloader workers\r\n",
      "Logging results to \u001B[1mmodels/yolov5/runs/train/exp\u001B[0m\r\n",
      "Starting training for 2 epochs...\r\n",
      "\r\n",
      "     Epoch   gpu_mem       box       obj       cls    labels  img_size\r\n",
      "       0/1     4.67G    0.1214   0.01194   0.07344        97       320:   0%|   /mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in ConvolutionBackward0. Traceback of forward call that caused the error:\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 337, in train\r\n",
      "    pred = model(imgs)  # forward\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 126, in forward\r\n",
      "    return self._forward_once(x, profile, visualize)  # single-scale inference, train\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 149, in _forward_once\r\n",
      "    x = m(x)  # run\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/models/yolo.py\", line 52, in forward\r\n",
      "    x[i] = self.m[i](x[i])  # conv\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/module.py\", line 1110, in _call_impl\r\n",
      "    return forward_call(*input, **kwargs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 447, in forward\r\n",
      "    return self._conv_forward(input, self.weight, self.bias)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/nn/modules/conv.py\", line 443, in _conv_forward\r\n",
      "    return F.conv2d(input, weight, bias, self.stride,\r\n",
      " (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)\r\n",
      "  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "       0/1     4.67G    0.1214   0.01194   0.07344        97       320:   0%|   \r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 650, in <module>\r\n",
      "    main(opt)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 546, in main\r\n",
      "    train(opt.hyp, opt, device, callbacks)\r\n",
      "  File \"/home/jonathan/PycharmProjects/IFT6759_Deep_learning/models/yolov5/train.py\", line 345, in train\r\n",
      "    scaler.scale(loss).backward()\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/_tensor.py\", line 363, in backward\r\n",
      "    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/autograd/__init__.py\", line 173, in backward\r\n",
      "    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass\r\n",
      "RuntimeError: Unable to find a valid cuDNN algorithm to run convolution\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "Exception ignored in: <function StorageWeakRef.__del__ at 0x7fc853fd65f0>\r\n",
      "Traceback (most recent call last):\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/multiprocessing/reductions.py\", line 36, in __del__\r\n",
      "  File \"/mnt/77A80709148517D5/IFT6759_Deep_learning/venv/lib/python3.10/site-packages/torch/storage.py\", line 520, in _free_weak_ref\r\n",
      "AttributeError: 'NoneType' object has no attribute '_free_weak_ref'\r\n",
      "sh: 1: source: not found\r\n",
      "Using cache found in /home/jonathan/.cache/torch/hub/pytorch_vision_v0.10.0\r\n",
      "The model has now been successfully loaded into memory\r\n",
      "The data has now been loaded successfully into memory\r\n",
      "Starting training now\r\n",
      "  0%|                                                     | 0/2 [00:00<?, ?it/s]\r\n",
      "  0%|                                                   | 0/232 [00:00<?, ?it/s]\u001B[A\r\n",
      "  0%|▏                                          | 1/232 [00:03<11:53,  3.09s/it]\u001B[A\r\n",
      "  1%|▎                                          | 2/232 [00:03<05:25,  1.42s/it]\u001B[A\r\n",
      "  1%|▌                                          | 3/232 [00:03<03:24,  1.12it/s]\u001B[A\r\n",
      "  2%|▋                                          | 4/232 [00:03<02:27,  1.55it/s]\u001B[A\r\n",
      "  2%|▉                                          | 5/232 [00:04<01:56,  1.95it/s]\u001B[A\r\n",
      "  3%|█                                          | 6/232 [00:04<01:38,  2.29it/s]\u001B[A\r\n",
      "  3%|█▎                                         | 7/232 [00:04<01:25,  2.62it/s]\u001B[A\r\n",
      "  3%|█▍                                         | 8/232 [00:04<01:17,  2.90it/s]\u001B[A\r\n",
      "  4%|█▋                                         | 9/232 [00:05<01:11,  3.12it/s]\u001B[A\r\n",
      "  4%|█▊                                        | 10/232 [00:05<01:07,  3.29it/s]\u001B[A\r\n",
      "  5%|█▉                                        | 11/232 [00:06<01:25,  2.58it/s]\u001B[A\r\n",
      "  5%|██▏                                       | 12/232 [00:06<01:17,  2.84it/s]\u001B[A\r\n",
      "  6%|██▎                                       | 13/232 [00:06<01:11,  3.06it/s]\u001B[A\r\n",
      "  6%|██▌                                       | 14/232 [00:06<01:07,  3.24it/s]\u001B[A\r\n",
      "  6%|██▋                                       | 15/232 [00:07<01:04,  3.38it/s]\u001B[A\r\n",
      "  7%|██▉                                       | 16/232 [00:07<01:25,  2.51it/s]\u001B[A\r\n",
      "  7%|███                                       | 17/232 [00:08<01:17,  2.77it/s]\u001B[A\r\n",
      "  8%|███▎                                      | 18/232 [00:08<01:11,  3.00it/s]\u001B[A\r\n",
      "  8%|███▍                                      | 19/232 [00:08<01:06,  3.19it/s]\u001B[A\r\n",
      "  9%|███▌                                      | 20/232 [00:08<01:03,  3.34it/s]\u001B[A\r\n",
      "  9%|███▊                                      | 21/232 [00:09<01:31,  2.31it/s]\u001B[A\r\n",
      "  9%|███▉                                      | 22/232 [00:09<01:20,  2.61it/s]\u001B[A\r\n",
      " 10%|████▏                                     | 23/232 [00:10<01:12,  2.86it/s]\u001B[A\r\n",
      " 10%|████▎                                     | 24/232 [00:10<01:07,  3.08it/s]\u001B[A\r\n",
      " 11%|████▌                                     | 25/232 [00:10<01:03,  3.25it/s]\u001B[A\r\n",
      " 11%|████▋                                     | 26/232 [00:11<01:21,  2.53it/s]\u001B[A"
     ]
    }
   ],
   "source": [
    "! python run_train.py --model yolo --dataset 2 --epoch 2\n",
    "! python run_train.py --model alexnet --dataset 2 --epoch 2"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "# Now lets test our model!\n",
    "\n",
    "To see the usage of the detect function we do :"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "! python run_detect.py -h"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "markdown",
   "source": [
    "Now lets continue with our alexnet example (assuming you have done the training!)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%% md\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [
    "! python run_detect.py --model alexnet --dataset 2 --test set unseen"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}